{% set name = "delta-spark" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/delta-io/delta/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d291d623014e47245b8e0d67a5d960585a1060bf7c52822f53d615ae744edd7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyspark <3.4.0,>=3.3.0
    - importlib-metadata >=1.0.0

test:
  imports:
    - delta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/delta-io/delta/
  summary: Python APIs for using Delta Lake with Apache Spark
  license: Apache-2.0
  license_file:
    - NOTICE.txt
    - LICENSE.txt
  doc_url: https://docs.delta.io
  dev_url: https://github.com/delta-io/delta

extra:
  recipe-maintainers:
    - scottsand-db
    - allisonport-db
    - nkarpov
